# Generated by Django 5.1.5 on 2025-01-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
